log_dir: /Users/syu/project/ml/ai_chat/mcp_agent/logs
mcp_model:
  api_key: sk-91be0fb7bcff47769fd6284527113cb6
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: deepseek-v3.2
datasource:
  host: 127.0.0.1
  port: 3306
  user: root
  password: '1234'
  database: ai

oss:
  endpoint: https://www.ufoyy.top:9000
  access-key: admin
  secret-key: n7d3t7x7
  bucket-name: app